# Generated by Django 2.2.4 on 2019-10-24 09:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='employeemodel',
            name='contact',
            field=models.IntegerField(default=False),
        ),
    ]
